// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "3-Clause BSD License",
            "url": "https://github.com/cyverse-de/app-exposer?tab=License-1-ov-file#readme"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/batch/launch": {
            "post": {
                "description": "Launch a batch analysis",
                "summary": "Launch a batch analysis",
                "operationId": "batch-launch",
                "parameters": [
                    {
                        "description": "Analysis Definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httphandlers.AnalysisLaunch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/batch/stop/{id}": {
            "delete": {
                "description": "Stop a batch analysis by its external UUID",
                "summary": "Stop a batch analysis by its external UUID",
                "operationId": "batch-stop",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cleanup": {
            "post": {
                "description": "Stop a batch analysis by its external UUID",
                "consumes": [
                    "application/json"
                ],
                "summary": "Stop a batch analysis by its external UUID",
                "operationId": "batch-cleanup",
                "parameters": [
                    {
                        "description": "External UUID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httphandlers.uuidBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/analyses/{analysis-id}/exit": {
            "post": {
                "description": "Terminates the VICE analysis based on the analysisID and\nand should not require any user information to be provided. Otherwise, the\ndocumentation for VICEExit applies here as well.",
                "summary": "Terminates a VICE analysis",
                "operationId": "admin-exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The external ID of the VICE analysis",
                        "name": "analysis-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/analyses/{analysis-id}/external-id": {
            "get": {
                "description": "Returns the external ID associated with the provided analysis ID.\nOnly returns the first external ID in multi-step analyses.",
                "summary": "Returns external ID",
                "operationId": "admin-get-external-id",
                "parameters": [
                    {
                        "maxLength": 36,
                        "minLength": 36,
                        "type": "string",
                        "description": "analysis UUID",
                        "name": "analysis-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.ExternalIDResp"
                        }
                    },
                    "400": {
                        "description": "id parameter is empty",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/analyses/{}/save-and-exit": {
            "post": {
                "description": "Handles requests to save the output files in iRODS and\nthen exit. This version of the call operates based on the analysis ID and does\nnot require user information to be required by the caller. Otherwise, the docs\nfor the VICESaveAndExit function apply here as well.",
                "summary": "Admin endpoint to trigger output file transfer and analysis exit",
                "operationId": "admin-save-and-exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Analysis ID",
                        "name": "analysis-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/terminate-all": {
            "post": {
                "description": "Terminates all analyses marked as running in the DE database.\nDoes not check for analyses in the cluster but not marked as running in the database.\nTerminates both VICE and batch analyses.",
                "summary": "Terminates all analyses",
                "operationId": "terminate-all-analyses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.TerminateAllResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/{host}/url-ready": {
            "get": {
                "description": "Handles requests to check the status of a running VICE app in K8s.\nThis will return an overall status and status for the individual containers in\nthe app's pod. Uses the state of the readiness checks in K8s, along with the\nexistence of the various resources created for the app.",
                "produces": [
                    "application/json"
                ],
                "summary": "Checks the status of a running VICE app in K8s",
                "operationId": "admin-url-ready",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The subdomain of the analysis",
                        "name": "host",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.URLReadyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/apply-labels": {
            "post": {
                "description": "Asynchronously applies labels to all running VICE analyses.\nThe application of the labels may not be complete by the time the response is returned.",
                "summary": "Applies labels to running VICE analyses.",
                "operationId": "apply-async-labels",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/async-data": {
            "get": {
                "description": "Returns data that is applied to analyses outside of an API call.\nThe returned data is not returned asynchronously, despite the name of the call.",
                "summary": "Returns data that is generately asynchronously from the job launch.",
                "operationId": "async-data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External ID",
                        "name": "external-id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.AsyncData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/launch": {
            "post": {
                "description": "The HTTP handler that orchestrates the launching of a VICE analysis inside\nthe k8s cluster. This gets passed to the router to be associated with a route. The Job\nis passed in as the body of the request.",
                "consumes": [
                    "application/json"
                ],
                "summary": "Launch a VICE analysis",
                "operationId": "launch-app",
                "parameters": [
                    {
                        "description": "The request body containing the analysis details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httphandlers.AnalysisLaunch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/{analysis-id}/logs": {
            "get": {
                "description": "Handlers requests to access the container logs for a pod in a running\nVICE app.",
                "produces": [
                    "application/json"
                ],
                "summary": "Return the logs for a running analysis",
                "operationId": "logs",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Whether to return previously terminated container logs",
                        "name": "previous",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The number of seconds in the past to begin showing logs",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The number of seconds since the epoch to begin showing logs",
                        "name": "since-time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The number of lines from the end of the log to show",
                        "name": "tail-lines",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to display timestamps at the beginning of each log line",
                        "name": "timestamps",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "The name of the container to display logs from",
                        "name": "container",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.VICELogEntry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/{host}/url-ready": {
            "get": {
                "description": "Returns whether or not a VICE app is ready\nfor users to access it. This version will check the user's permissions\nand return an error if they aren't allowed to access the running app.",
                "produces": [
                    "application/json"
                ],
                "summary": "Check if a VICE app is ready for users to access it.",
                "operationId": "url-ready",
                "parameters": [
                    {
                        "type": "string",
                        "description": "A user's username",
                        "name": "user",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The subdomain of the analysis. AKA the ingress name",
                        "name": "host",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.URLReadyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/{id}/exit": {
            "post": {
                "description": "Terminates the VICE analysis deployment and cleans up\nresources asscociated with it. Does not save outputs first. Uses\nthe external-id label to find all of the objects in the configured\nnamespace associated with the job. Deletes the following objects:\ningresses, services, deployments, and configmaps.",
                "summary": "Terminates a VICE analysis",
                "operationId": "exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The external ID of the VICE analysis",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/{id}/save-and-exit": {
            "post": {
                "description": "Handles requests to save the output files in iRODS and then exit.\nThe exit portion will only occur if the save operation succeeds. The operation is\nperformed inside of a goroutine so that the caller isn't waiting for hours/days for\noutput file transfers to complete.",
                "summary": "Save files and terminate VICE analysis",
                "operationId": "save-and-exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "external ID of the analysis",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error_code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httphandlers.AnalysisLaunch": {
            "type": "object"
        },
        "httphandlers.AsyncData": {
            "type": "object",
            "properties": {
                "analysisID": {
                    "type": "string"
                },
                "ipAddr": {
                    "type": "string"
                },
                "subdomain": {
                    "type": "string"
                }
            }
        },
        "httphandlers.ExternalIDResp": {
            "type": "object",
            "properties": {
                "external_id": {
                    "type": "string",
                    "example": "bb52aefb-e021-4ece-89e5-fd73ce30643c"
                }
            }
        },
        "httphandlers.TerminateAllResponse": {
            "type": "object",
            "properties": {
                "batch": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "failed_batch": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "failed_vice": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "vice": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "httphandlers.URLReadyResponse": {
            "type": "object",
            "properties": {
                "ready": {
                    "type": "boolean"
                }
            }
        },
        "httphandlers.VICELogEntry": {
            "type": "object",
            "properties": {
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "since_time": {
                    "type": "string"
                }
            }
        },
        "httphandlers.uuidBody": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:60000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "app-exposer",
	Description:      "The app-exposer API for the Discovery Environment's VICE feature.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
