// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "3-Clause BSD License",
            "url": "https://github.com/cyverse-de/app-exposer?tab=License-1-ov-file#readme"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/batch/launch": {
            "post": {
                "description": "Launch a batch analysis",
                "summary": "Launch a batch analysis",
                "operationId": "batch-launch",
                "parameters": [
                    {
                        "description": "Analysis Definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httphandlers.AnalysisLaunch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/batch/stop/{id}": {
            "delete": {
                "description": "Stop a batch analysis by its external UUID",
                "summary": "Stop a batch analysis by its external UUID",
                "operationId": "batch-stop",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cleanup": {
            "post": {
                "description": "Stop a batch analysis by its external UUID",
                "consumes": [
                    "application/json"
                ],
                "summary": "Stop a batch analysis by its external UUID",
                "operationId": "batch-cleanup",
                "parameters": [
                    {
                        "description": "External UUID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httphandlers.uuidBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/analyses/{analysis-id}/exit": {
            "post": {
                "description": "Terminates the VICE analysis based on the analysisID and\nand should not require any user information to be provided. Otherwise, the\ndocumentation for VICEExit applies here as well.",
                "summary": "Terminates a VICE analysis",
                "operationId": "admin-exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The external ID of the VICE analysis",
                        "name": "analysis-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/analyses/{analysis-id}/external-id": {
            "get": {
                "description": "Returns the external ID associated with the provided analysis ID.\nOnly returns the first external ID in multi-step analyses.",
                "summary": "Returns external ID",
                "operationId": "admin-get-external-id",
                "parameters": [
                    {
                        "maxLength": 36,
                        "minLength": 36,
                        "type": "string",
                        "description": "analysis UUID",
                        "name": "analysis-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.ExternalIDResp"
                        }
                    },
                    "400": {
                        "description": "id parameter is empty",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/analyses/{}/save-and-exit": {
            "post": {
                "description": "Handles requests to save the output files in iRODS and\nthen exit. This version of the call operates based on the analysis ID and does\nnot require user information to be required by the caller. Otherwise, the docs\nfor the VICESaveAndExit function apply here as well.",
                "summary": "Admin endpoint to trigger output file transfer and analysis exit",
                "operationId": "admin-save-and-exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Analysis ID",
                        "name": "analysis-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/admin/terminate-all": {
            "post": {
                "description": "Terminates all analyses marked as running in the DE database.\nDoes not check for analyses in the cluster but not marked as running in the database.\nTerminates both VICE and batch analyses.",
                "summary": "Terminates all analyses",
                "operationId": "terminate-all-analyses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.TerminateAllResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/apply-labels": {
            "post": {
                "description": "Asynchronously applies labels to all running VICE analyses.\nThe application of the labels may not be complete by the time the response is returned.",
                "summary": "Applies labels to running VICE analyses.",
                "operationId": "apply-async-labels",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/async-data": {
            "get": {
                "description": "Returns data that is applied to analyses outside of an API call.\nThe returned data is not returned asynchronously, despite the name of the call.",
                "summary": "Returns data that is generately asynchronously from the job launch.",
                "operationId": "async-data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External ID",
                        "name": "external-id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httphandlers.AsyncData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/{id}/exit": {
            "post": {
                "description": "Terminates the VICE analysis deployment and cleans up\nresources asscociated with it. Does not save outputs first. Uses\nthe external-id label to find all of the objects in the configured\nnamespace associated with the job. Deletes the following objects:\ningresses, services, deployments, and configmaps.",
                "summary": "Terminates a VICE analysis",
                "operationId": "exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The external ID of the VICE analysis",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vice/{id}/save-and-exit": {
            "post": {
                "description": "Handles requests to save the output files in iRODS and then exit.\nThe exit portion will only occur if the save operation succeeds. The operation is\nperformed inside of a goroutine so that the caller isn't waiting for hours/days for\noutput file transfers to complete.",
                "summary": "Save files and terminate VICE analysis",
                "operationId": "save-and-exit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "external ID of the analysis",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error_code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httphandlers.AnalysisLaunch": {
            "type": "object"
        },
        "httphandlers.AsyncData": {
            "type": "object",
            "properties": {
                "analysisID": {
                    "type": "string"
                },
                "ipAddr": {
                    "type": "string"
                },
                "subdomain": {
                    "type": "string"
                }
            }
        },
        "httphandlers.ExternalIDResp": {
            "type": "object",
            "properties": {
                "external_id": {
                    "type": "string",
                    "example": "bb52aefb-e021-4ece-89e5-fd73ce30643c"
                }
            }
        },
        "httphandlers.TerminateAllResponse": {
            "type": "object",
            "properties": {
                "batch": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "failed_batch": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "failed_vice": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "vice": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "httphandlers.uuidBody": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:60000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "app-exposer",
	Description:      "The app-exposer API for the Discovery Environment's VICE feature.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
