basePath: /
definitions:
  common.ErrorResponse:
    properties:
      details:
        additionalProperties: true
        type: object
      error_code:
        type: string
      message:
        type: string
    type: object
  httphandlers.ExternalIDResp:
    properties:
      'external_id example:':
        type: string
    type: object
host: localhost:60000
info:
  contact: {}
  description: The app-exposer API for the Discovery Environment's VICE feature.
  license:
    name: 3-Clause BSD License
    url: https://github.com/cyverse-de/app-exposer?tab=License-1-ov-file#readme
  title: app-exposer
  version: "1.0"
paths:
  /vice/admin/analyses/{analysis-id}/external-id:
    get:
      description: |-
        Returns the external ID associated with the provided analysis ID.
        Only returns the first external ID in multi-step analyses.
      operationId: admin-get-external-id
      parameters:
      - description: analysis UUID
        in: path
        maxLength: 36
        minLength: 36
        name: analysis-id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httphandlers.ExternalIDResp'
        "400":
          description: id parameter is empty
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Returns external ID
swagger: "2.0"
